project_name: datadog-slo-insufflate
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: datadog-slo-insufflate
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
release:
  prerelease: auto